# This directory is entirely composed of the open source projects
#
#   https://github.com/open-source-parsers/jsoncpp  (MIT license) included as amalgamated source.

cc_library(name = "json",
           srcs = ["jsoncpp.cpp",
                   "json.h",
                   "json-forwards.h"],
           visibility = ["//visibility:public"])

